Vagrant.configure("2") do |config|
    config.vm.box = "bento/debian-9.6"
  
    config.vm.define "web" do |web|
      web.vm.hostname = "web"
      web.vm.network :private_network, ip: "10.5.2.5"
  
      web.vm.provision "file", source: "config-default.php", destination: "/tmp/config-default.php"
      web.vm.provision "shell", path: "web.sh"
    end
  
    config.vm.define "db" do |db|
      db.vm.hostname = "db"
      db.vm.network :private_network, ip: "10.5.3.5"
  
      db.vm.provision "shell", path: "db.sh"
    end
  end
  